### ISSUE TITLE
试用项目遇到的BUG

### ISSUE THREAD

**Issue by HuanMeng0** [tonyxyl/laravel_admin_api#2]
2014_10_12_000000_create_users_table.php
第19行错误

2018_02_06_144642_create_lotto_table.php
第21行漏括号。

PermissionSeeder.php
App\Models\User 应该改为App\Models\AdminUser 

运行环境是Laravel Homestead

**Comment by lonycc** [comment]
后期数据库更改较大，我都是直接操作数据库，没有用迁移命令。多谢指正，已更新。
