### ISSUE TITLE
执行 php artisan config:cache后，项目将会报错，具体错误信息如下

### ISSUE THREAD

**Issue by blibli10086** [tonyxyl/laravel_admin_api#3]
Fatal error: Uncaught ReflectionException: Class config does not exist in F:\myOnlineSvn\tongmeng\backend\vendor\laravel\framework\src\Illuminate\Container\Container.php:752 Stack trace: #0 F:\myOnlineSvn\tongmeng\backend\vendor\laravel\framework\src\Illuminate\Container\Container.php(752): ReflectionClass->__construct('config') #1 F:\myOnlineSvn\tongmeng\backend\vendor\laravel\framework\src\Illuminate\Container\Container.php(631): Illuminate\Container\Container->build('config') #2 F:\myOnlineSvn\tongmeng\backend\vendor\laravel\framework\src\Illuminate\Container\Container.php(586): Illuminate\Container\Container->resolve('config', Array) #3 F:\myOnlineSvn\tongmeng\backend\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(732): Illuminate\Container\Container->make('config', Array) #4 F:\myOnlineSvn\tongmeng\backend\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(110): Illuminate\Foundation\Application->make('config', Array) #5 F:\myOnlineSvn\tongmeng\backend\vendor\laravel\framework\src\Illu in F:\myOnlineSvn\tongmeng\backend\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 752

**Comment by lonycc** [comment]
贴出完整报错吧，这个我在本地是没有错误的。有可能是你执行`composer install`时有些依赖没安装成功。

**Comment by lonycc** [comment]
本地重现了这个问题，删掉这个文件`boostrap/cache/config.php`即可正常。
