### ISSUE TITLE
发现数据表上有点小瑕疵

### ISSUE THREAD

**Issue by dreamsleet** [tonyxyl/laravel_admin_api#4]
首先感谢大神，东西我拿来在学习中。初学laravel，有空望多指教。
1,
In 2018_02_06_144642_create_lotto_table.php line 21:
  Call to a member function default() on null
原因：没有设置realname字段允许为，后面写入数据时没有没有realname值
 $table->string('realname')->unique()->nullable();
2,
In 2018_02_06_144642_create_lotto_table.php line 21:
  Call to a member function default() on null
 $table->integer('update_user')->nullable->default(0);   nullable后面少了括号

**Comment by lonycc** [comment]
已修正。
